# Numpy

[NumPy](https://numpy.org/doc/stable/user/whatisnumpy.html) (__Numerical Python__) - фундаметальная библиотека для научных вычислений в Python. Главными особенностями являются: доступность (open source) и скорость вычислений.

In [1]:
import numpy as np

### Объявление массива

#### Одномерный массив 

In [2]:
ar = np.array([0, 4, 1.1, -12])

Узнать размер массива можно используя метод `shape`. Еще существует метод `size`, который возвращает число элементов массива

In [3]:
ar.shape

(4,)

In [4]:
ar.size

4

#### Двумерный массив

In [5]:
ar_2d = np.array([[1, 2], 
                  [3, 4]])

In [6]:
ar_2d.shape

(2, 2)

In [7]:
ar_2d.size

4

#### Многомерные массивы


Трехмерный массив из нулей

In [8]:
ar_3d = np.zeros((3, 2, 2))

In [9]:
ar_3d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Массив из единиц


In [10]:
ar_ones = np.ones((5, 5))

In [11]:
ar_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Массив из единиц на диагонали

In [12]:
ar_eye = np.eye(4, 5)

In [13]:
ar_eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [14]:
ar_eye_up = np.eye(4, 5, k=1)

In [15]:
ar_eye_up

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Можно задавать массивы различных размерностей из произвольных чисел или из чисел, распределенных по некоторому закону

In [16]:
rand_1d = np.random.sample(10)
rand_1d

array([0.09835919, 0.23429947, 0.04938549, 0.6357343 , 0.088219  ,
       0.20570437, 0.61678507, 0.05924878, 0.84904339, 0.84272236])

In [17]:
rand_int = np.random.randint(low = 1, high = 10, size = 10)
rand_int

array([5, 3, 5, 8, 6, 8, 7, 6, 3, 3])

### Основные операции с массивами

Итак, мы научились создавать массивы произвольных размерностей. Давайте теперь посмотрим, какие операции над ними нам доступны 

Важным отличием от встроенных в Python списков является то, что для `numpy` все стандартные операции выполняются поэлементно

In [18]:
ar1 = np.array([1, 2, 3, 4, 5])
ar2 = np.array([6, 7, 8, 9, 10])

print(ar1 + ar2)   # Сложение
print(ar1 - ar2)   # Вычитание
print(ar1 * ar2)   # Умножение
print(ar1 / ar2)   # Деление
print(ar1 ** ar2)  # Возведение в степень
print(ar1 // ar2)  # Целая часть от деления
print(ar1 % ar2)   # Остаток от деления

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[0 0 0 0 0]
[1 2 3 4 5]


Также доступны и операции с числами

In [19]:
print(ar1 + 5)
print(ar1 - 5)
print(ar1 * 5)
print(ar1 / 5)
print(ar1 ** 5)
print(ar1 // 5)  
print(ar1 % 5) 

[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[   1   32  243 1024 3125]
[0 0 0 0 1]
[1 2 3 4 0]


Стоит заметить, что массивы `numpy.ndarray` изменяемый тип данных

In [20]:
print(ar1)
ar1[0] = 100
print(ar1)

[1 2 3 4 5]
[100   2   3   4   5]


При необходимости вычленить определенные элементы из массива, отвечающие некоторому условию, можно использовать так называемые "маски"

In [21]:
ar = np.random.randint(-25, 25, 50)

In [22]:
ar

array([ 20,  10,   2,  10,  -8,  18,   7,  16, -14, -22,   8,   8,  -1,
        -8,  21, -24, -20,  21,   5,  21, -24,  11,   7,   6,   4, -16,
        -8,  13, -24,   8,  21, -19,  19,  -2,   5,  16, -19,  18,   6,
       -14,  24,   6,  22,  15,  -9,  -2,   9,   6,  17,   2])

In [23]:
ar[ar > 10]

array([20, 18, 16, 21, 21, 21, 11, 13, 21, 19, 16, 18, 24, 22, 15, 17])

Есть возможность задавать более сложные условия

In [24]:
ar[(ar > 10) & (ar < 20)]

array([18, 16, 11, 13, 19, 16, 18, 15, 17])

Как это работает?

In [25]:
ar > 10

array([ True, False, False, False, False,  True, False,  True, False,
       False, False, False, False, False,  True, False, False,  True,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False,  True, False,  True, False, False,  True,
       False,  True, False, False,  True, False,  True,  True, False,
       False, False, False,  True, False])

То есть при задании условия каждый элемент массива проверяется на соответствие заданному условию и формируется булевый массив. Важно, что созданный нами массив такой же длины, что и исходный, поэтому интерпретатор Python понимает какой элемент необходимо вернуть.

Для этой задачи также подходит функция `where`, которая позволяет находить индексы элементов, которые подпадают под заданное условие.

In [26]:
indexes = np.where(ar > 10)
indexes

(array([ 0,  5,  7, 14, 17, 19, 21, 27, 30, 32, 35, 37, 40, 42, 43, 48],
       dtype=int64),)

In [27]:
ar[indexes]

array([20, 18, 16, 21, 21, 21, 11, 13, 21, 19, 16, 18, 24, 22, 15, 17])

In [28]:
ar_2d = np.random.randint(-25, 25, size=(4, 10))
indexes_2d = np.where(ar_2d > 10)
indexes_2d

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3], dtype=int64),
 array([2, 7, 8, 2, 5, 7, 1, 5, 6, 7, 3, 4, 5], dtype=int64))

In [29]:
ar_2d[indexes_2d]

array([15, 20, 16, 18, 15, 12, 21, 17, 16, 18, 16, 16, 12])

Так же, как и для масок, можно делать сложные условия

In [30]:
indexes_2d = np.where((ar_2d > 10) & (ar_2d < 20))
ar_2d[indexes_2d]

array([15, 16, 18, 15, 12, 17, 16, 18, 16, 16, 12])

Кроме того функция where позволяет проводить фильтрацию элементов и заменять "плохие" элементы некоторыми другими значениями

In [31]:
np.where(ar_2d > 10, ar_2d, 0)

array([[ 0,  0, 15,  0,  0,  0,  0, 20, 16,  0],
       [ 0,  0, 18,  0,  0, 15,  0, 12,  0,  0],
       [ 0, 21,  0,  0,  0, 17, 16, 18,  0,  0],
       [ 0,  0,  0, 16, 16, 12,  0,  0,  0,  0]])

In [32]:
np.where(ar_2d > 10, 20, 0)

array([[ 0,  0, 20,  0,  0,  0,  0, 20, 20,  0],
       [ 0,  0, 20,  0,  0, 20,  0, 20,  0,  0],
       [ 0, 20,  0,  0,  0, 20, 20, 20,  0,  0],
       [ 0,  0,  0, 20, 20, 20,  0,  0,  0,  0]])

### Некоторые функции `numpy`

В библиотеке `numpy` реализовано множество дополнительных функций. С ними можно ознакомиться на странице с [документацией](https://numpy.org/doc/1.16/reference/routines.random.html). 
Здесь же мы отметим пару наиболее часто употребляемых функций.


Например, хотим создать массив из чисел от -1 до 1 с шагом 0.2, функция range работает лишь с целыми числами и не справляется с этой задачей

In [33]:
range(-1, 1, 0.2)

TypeError: 'float' object cannot be interpreted as an integer

В `numpy` есть несколько функций для этой цели, функция linspace разбивает заданный отрезок на указанное число элементов. В данном примере отрезок от -1 до 1 рабивается  на 11 элементов, включая правую границу отрезка

In [34]:
t = np.linspace(-1, 1, 11)
print(t)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8  1. ]


Если мы не хотим включать правую границу, необходимо в именнованный аргумент endpoint передать значение False

In [35]:
t = np.linspace(-1, 1, 10, endpoint=False)
print(t)

[-1.  -0.8 -0.6 -0.4 -0.2  0.   0.2  0.4  0.6  0.8]


Также есть функция arange которая разбивает заданный отрезок уже с определенным шагом, для нее правая граница отрезка не включается по умолчанию

In [36]:
t = np.arange(-1, 1, 0.2)
print(t)

[-1.00000000e+00 -8.00000000e-01 -6.00000000e-01 -4.00000000e-01
 -2.00000000e-01 -2.22044605e-16  2.00000000e-01  4.00000000e-01
  6.00000000e-01  8.00000000e-01]


Алгоритм сортировки

In [37]:
a = np.random.randint(-10, 10, 15)
print(a)
print(np.sort(a))

[ 6  2 -1  2  8 -2  3 -7  7 -1  1  9  0  1 -2]
[-7 -2 -2 -1 -1  0  1  1  2  2  3  6  7  8  9]


Функция выше возвращает отсортированную копию массива. Если нужна сортировка самого массива без копий:

In [38]:
a.sort()
a

array([-7, -2, -2, -1, -1,  0,  1,  1,  2,  2,  3,  6,  7,  8,  9])

Также иногда бывает полезно получить только список индексов, соответствующих отсортированному массиву

In [39]:
a = np.random.randint(-10, 10, 15)
print(f"Элменты: {a}")
print(f"Индексы для отсортированного массива: {np.argsort(a)}")
print(f"Отсортированный массив: {a[np.argsort(a)]}")

Элменты: [-7  6  4 -2 -6  9  2 -5 -7  9 -1 -8 -6 -7 -3]
Индексы для отсортированного массива: [11  0  8 13  4 12  7 14  3 10  6  2  1  5  9]
Отсортированный массив: [-8 -7 -7 -7 -6 -6 -5 -3 -2 -1  2  4  6  9  9]


Найти индекс максимального или минимального элемента

In [40]:
print(np.argmax(a))
a[np.argmax(a)]

5


9

In [41]:
print(np.argmin(a))
a[np.argmin(a)]

11


-8

#### Сумма

Для расчета суммы элементов массива используется функция sum, при работе с одномерными массивами она ведет сбея также как и встроенная функция sum

In [42]:
a = np.array([1, 2, 3, 4])
print(np.sum(a))
print(sum(a))

10
10


Однако для многомерных массивов это уже не так. Например у нас есть матрица а

In [43]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [44]:
print(np.sum(a))
print(sum(a))

10
[4 6]


In [45]:
np.sum(a, axis = 0)

array([4, 6])

In [46]:
np.sum(a, axis = 1)

array([3, 7])

Норма

$||x|| = \sqrt{\sum_i {x^2_i}}$

Бывает необходимо посчитать, норму нашего массива. Определим норму массива как корень из суммы квадратов его элементов. Мы конечно можем задать эту формулу напрямую, однако в `numpy` есть функция, которая может сделать это за нас

In [47]:
a = np.array([1, 2, 3, 4])
np.sum(a**2)**0.5

5.477225575051661

In [48]:
np.linalg.norm(a)

5.477225575051661

Ее преимущество состоит в том, что как и для суммы мы можем задать ось вдоль которой вычисляется норма. Если мы хотим посчитать норму массива, элементами которого будут наши строки, то необходимо аргумент axis задать нулем

In [49]:
a = np.array([[3, 4], [6, 8]])
a

array([[3, 4],
       [6, 8]])

In [50]:
np.linalg.norm(a, axis = 0)

array([6.70820393, 8.94427191])

Если мы хотим посчитать норму массива, элементами которого будут столбцы, то axis уже должен равняться единице

In [51]:
np.linalg.norm(a, axis = 1)

array([ 5., 10.])

Другие функции Numpy

In [52]:
# cos, sin, exp и т.д.
t = np.array([np.pi, 0])
print('cos = ', np.cos(t))
print('sin = ', np.sin(t))
print('exp = ', np.exp(-1j * t))
print('гиперолический синус = ', np.sinh(t))

cos =  [-1.  1.]
sin =  [1.2246468e-16 0.0000000e+00]
exp =  [-1.-1.2246468e-16j  1.-0.0000000e+00j]
гиперолический синус =  [11.54873936  0.        ]


Множество операций с матрицами

In [54]:
a = np.array([[0, 1], [1, 0]])
b = 2 * np.eye(2)

In [57]:
print('Поэлементное умножение = \n', a * b)

Поэлементное умножение = 
 [[0. 0.]
 [0. 0.]]


In [58]:
print('Матричное умножение = \n', np.dot(a, b))

Матричное умножение = 
 [[0. 2.]
 [2. 0.]]


In [62]:
print('Диагональ а = ', np.diagonal(a))

Диагональ а =  [0 0]


In [60]:
print('Собственные значения и функции а = \n', np.linalg.eig(a))

Собственные значения и функции а = 
 (array([ 1., -1.]), array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]]))


In [61]:
print('Обратная матрица для b = \n', np.linalg.inv(b))

Обратная матрица для b = 
 [[0.5 0. ]
 [0.  0.5]]


Также есть возможность записывать и считывать одномерные и двумерные массивы с помощью функций `savetxt` и `loadtxt`. К примеру, здесь мы с помощью функции `savetxt` записываем массив `b` в файл с именем `123`, а с помощью функции `loadtxt` считываем массив из файла `123` в переменную `a`.

In [63]:
b = np.array([[1, 2, 3], [4, 5, 6]])
np.savetxt('123', b)
a = np.loadtxt('123')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


## Задачи

Массив задан дискретной функцией $f(t_i) = t_ie^t_i - t_i^4$, где $t_i \in [0, 5]$ с шагом $\Delta t = 0.001$. Необходимо найти максимальное значение массива на отрезке $t_i \in [0, 2]$, а также $t_{max}$ при котором оно достигается, а затем минимальное значение на промежутке $t_i \in [2, 5]$ и $t_{min}$ при котором оно достигается 

In [67]:
dt = 1e-03
t = np.arange(0, 5 + dt, dt)
f = t * np.exp(t) - t**4 

Найдем максимальное и минимальное значение массива на промежутке

In [70]:
print('maximum = ', f[t <= 2].max())
print('minimum = ', f[t >= 2].min())

maximum =  1.9216334091749405
minimum =  -38.78383461465896


или так 

In [71]:
print('maximum = ', np.max(f[t <= 2]))
print('minimum = ', np.min(f[t >= 2]))

maximum =  1.9216334091749405
minimum =  -38.78383461465896


Теперь посмотрим при каким значениям `t` они соответствуют

Первый способ

In [72]:
index = np.argmax(f[t <= 2])
f[index]

1.9216334091749405

In [76]:
tmax = t[t <= 2][index]
print(f'tmax = {tmax:.4f}')

tmax = 1.2550


Второй способ

In [77]:
fmax = f[t <= 2].max()
np.where(f == fmax)

(array([1255], dtype=int64),)

In [80]:
print(np.where(f == fmax)[0])
print(np.where(f == fmax)[0][0])

[1255]
1255


In [82]:
index = np.where(f == fmax)[0][0]
print(f'tmax = {tmax:.4f}')

tmax = 1.2550


Аналонично можно получить значение `t` для положения минимума.
Таким образом положения максимума и минимума:

In [86]:
index = f[t <= 2].argmax()
tmax = t[t <= 2][index]# первый вариант
print(f'I.  tmax = {tmax:.4f}')
index = np.where(f == f[t <= 2].max())[0][0]#второй вариант
print(f'II. tmax = {t[index]:.4f}')
index = f[t >= 2].argmin()
tmin = t[t >= 2][index]# первый вариант
print(f'I.  tmin = {tmin:.4f}')
index = np.where(f == f[t >= 2].min())[0][0]#второй вариант
print(f'II. tmin = {t[index]:.4f}')

I.  tmax = 1.2550
II. tmax = 1.2550
I.  tmin = 3.8540
II. tmin = 3.8540


№2. Напишите функции для преобразования координат из декартовой системы в сферическую и наоборот

Перейдем к решению задачи. Пусть имеется n точек с координатами $[x_i, y_i, z_i]$ для $i = 0,1,..,n-1$. Найдем для них координаты в сферической системе $[r_i, \theta_i, \phi_i]$, а потом для этих координат решим обратную задачу

In [87]:
n = 50
x = np.linspace(-10, 10, n)
y = np.linspace(-10, 10, n)
z = np.linspace(-10, 10, n)

$r = \sqrt{x^2 + y^2 + z^2}$

$\theta = arctg(\sqrt{x^2 + y^2} / z)$

$\phi = arctg(x / y)$

In [88]:
def cartesian_to_sphere(x, y, z):
    r = np.sqrt(x**2 + y**2 + z**2)
    theta = np.arctan2(np.sqrt(x**2 + y**2), z)
    phi = np.arctan2(y, x)
    return r, theta, phi

Посмотрим, что получается

In [90]:
r, theta, phi = cartesian_to_sphere(x, y, z)

In [91]:
print(r)

[17.32050808 16.61354856 15.90658905 15.19962954 14.49267002 13.78571051
 13.078751   12.37179148 11.66483197 10.95787246 10.25091294  9.54395343
  8.83699392  8.1300344   7.42307489  6.71611538  6.00915586  5.30219635
  4.59523684  3.88827732  3.18131781  2.4743583   1.76739878  1.06043927
  0.35347976  0.35347976  1.06043927  1.76739878  2.4743583   3.18131781
  3.88827732  4.59523684  5.30219635  6.00915586  6.71611538  7.42307489
  8.1300344   8.83699392  9.54395343 10.25091294 10.95787246 11.66483197
 12.37179148 13.078751   13.78571051 14.49267002 15.19962954 15.90658905
 16.61354856 17.32050808]


Теперь решим обратную задачу

$x = rsin(\theta)cos(\phi)$

$y = rsin(\theta)sin(\phi)$

$z = rcos(\theta)$


In [92]:
def sphere_to_cartesian(r, theta, phi):
    x = r * np.sin(theta) * np.cos(phi)
    y = r * np.sin(theta) * np.sin(phi)
    z = r * np.cos(theta)
    return x, y, z

Проверим наше решение

In [93]:
x_new, y_new, z_new = sphere_to_cartesian(r, theta, phi)

In [94]:
np.abs(x_new - x) < 1e-8

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [95]:
np.allclose(x, x_new) and np.allclose(y, y_new) and np.allclose(z, z_new)

True